spring.application.name=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Database Configuration
spring.datasource.url=${SERVICE_DB_URL:jdbc:mysql}
spring.datasource.username=${SERVICE_DB_USERNAME}
spring.datasource.password=${SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=${SERVICE_DB_DRIVER_CLASS_NAME}
spring.datasource.connection-timeout=${SERVICE_DB_CONNECTION_TIMEOUT
spring.datasource.maximum-pool-size=${SERVICE_DB_MAX_POOL_SIZE}
spring.datasource.minimum-idel=${SERVICE_DB_MIN_IDLE}
spring.datasource.pool-name=${SERVICE_DB_POOL_NAME}
spring.datasource.connection-test-query=${SERVICE_DB_TEST_QUERY}

# Application Payload Logging Helper
payload.logging.rules.filepath=cfg/json-payload-logging-rules.json

# Hibernate (optional, if using JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect